epp-br:
  test:
    host:     beta.registro.br
    username:
    password:
    ssl:
      cert: config/epp-br/client.pem
      key:  config/epp-br/client.pem
      ca:   config/epp-br/root.pem

  production:
    host:     registro.br
    username:
    password:
    ssl:
      cert: config/epp-br/client.pem
      key:  config/epp-br/client.pem
      ca:   config/epp-br/root.pem
